
import Head from 'next/head'
// import { FC } from 'react'
import { Navbar } from '../Navbar'
// import Link from 'next/link'
import styles from './MainLayout.module.css'

import { FC, ReactNode } from 'react';

interface Props {
  children: ReactNode;
}


export const MainLayout :FC<Props> = ({children}) => {
    
    return (
        <div className={styles.container}>
          <Head>
            <title>DIEGO CELIS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>             
          <main className={styles.main}>
                {children}
    
          </main>           
        </div>
      )
}
